"""Pydantic models for the Company Onboarding Wizard."""

from __future__ import annotations

import re

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Spec Parser output models
# ---------------------------------------------------------------------------

class ParsedOperation(BaseModel):
    """A single API operation extracted from an OpenAPI spec."""
    path: str
    method: str
    operation_id: str = ""
    summary: str = ""
    description: str = ""
    is_write: bool = False
    raw_parameters: list[dict] = Field(default_factory=list)
    raw_request_body: dict | None = None
    raw_responses: dict = Field(default_factory=dict)
    # x-agentcafe-* extensions if present
    preset_scope: str | None = None
    preset_human_auth: bool | None = None
    preset_rate_limit: str | None = None


class ParsedSpec(BaseModel):
    """Result of parsing an OpenAPI spec."""
    title: str
    version: str
    description: str = ""
    base_url: str = ""
    operations: list[ParsedOperation] = Field(default_factory=list)
    raw_spec: dict = Field(default_factory=dict)
    warnings: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# AI Enricher output models
# ---------------------------------------------------------------------------

class CandidateInput(BaseModel):
    """A required input field for an action."""
    name: str
    description: str = ""
    example: str | int | float | bool | list | dict | None = None
    type: str = "string"


class CandidateAction(BaseModel):
    """An enriched action ready for review."""
    action_id: str
    description: str = ""
    required_inputs: list[CandidateInput] = Field(default_factory=list)
    example_response: dict = Field(default_factory=dict)
    suggested_scope: str = ""
    suggested_human_auth: bool = False
    suggested_rate_limit: str = "60/minute"
    is_write: bool = False
    confidence: dict[str, float] = Field(default_factory=dict)
    source_path: str = ""
    source_method: str = ""


class CandidateMenuEntry(BaseModel):
    """A candidate Menu entry generated by the enricher."""
    service_id: str
    name: str
    category: str = ""
    capability_tags: list[str] = Field(default_factory=list)
    description: str = ""
    actions: list[CandidateAction] = Field(default_factory=list)
    confidence: dict[str, float] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Wizard API request/response models
# ---------------------------------------------------------------------------

class CompanyCreateRequest(BaseModel):
    """Request body for POST /wizard/companies."""
    name: str
    email: str
    password: str
    website: str = ""

    @field_validator("name")
    @classmethod
    def name_not_empty(cls, v: str) -> str:
        v = v.strip()
        if not v or len(v) > 200:
            raise ValueError("Name must be 1-200 characters.")
        return v

    @field_validator("email")
    @classmethod
    def email_valid(cls, v: str) -> str:
        if not re.match(r"^[^@\s]+@[^@\s]+\.[^@\s]+$", v):
            raise ValueError("Invalid email format.")
        return v.lower().strip()

    @field_validator("password")
    @classmethod
    def password_strong_enough(cls, v: str) -> str:
        if len(v) < 8:
            raise ValueError("Password must be at least 8 characters.")
        return v


class CompanyCreateResponse(BaseModel):
    """Response body for POST /wizard/companies."""
    company_id: str
    name: str
    email: str
    session_token: str


class CompanyLoginRequest(BaseModel):
    """Request body for POST /wizard/companies/login."""
    email: str
    password: str


class CompanyLoginResponse(BaseModel):
    """Response body for POST /wizard/companies/login."""
    company_id: str
    name: str
    session_token: str


class SpecParseRequest(BaseModel):
    """Request body for POST /wizard/specs/parse."""
    raw_spec: str


class SpecParseResponse(BaseModel):
    """Response body for POST /wizard/specs/parse."""
    draft_id: str
    parsed_spec: ParsedSpec
    candidate_menu: CandidateMenuEntry


class ReviewSaveRequest(BaseModel):
    """Request body for PUT /wizard/drafts/{draft_id}/review."""
    service_id: str
    name: str
    category: str = ""
    capability_tags: list[str] = Field(default_factory=list)
    description: str = ""
    actions: list[CandidateAction] = Field(default_factory=list)
    excluded_actions: list[str] = Field(default_factory=list)


class PolicyAction(BaseModel):
    """Per-action policy settings."""
    scope: str
    human_auth: bool = False
    rate_limit: str = "60/minute"


class PolicySaveRequest(BaseModel):
    """Request body for PUT /wizard/drafts/{draft_id}/policy."""
    actions: dict[str, PolicyAction]
    backend_url: str
    backend_auth_header: str = ""


class PreviewResponse(BaseModel):
    """Response body for GET /wizard/drafts/{draft_id}/preview."""
    final_menu_entry: dict
    proxy_configs: list[dict]


class DryRunResult(BaseModel):
    """Result of testing a single action's proxy mapping."""
    action_id: str
    status: str  # "ok" | "error"
    message: str = ""


class DryRunResponse(BaseModel):
    """Response body for POST /wizard/drafts/{draft_id}/dry-run."""
    results: list[DryRunResult]
    all_ok: bool


class PublishResponse(BaseModel):
    """Response body for POST /wizard/drafts/{draft_id}/publish."""
    service_id: str
    name: str
    actions_published: int
    message: str


# ---------------------------------------------------------------------------
# Post-publish management models
# ---------------------------------------------------------------------------

class ServiceDashboardResponse(BaseModel):
    """Response body for GET /wizard/services/{service_id}/dashboard."""
    service_id: str
    name: str
    description: str
    status: str
    published_at: str
    actions_count: int
    total_requests: int
    recent_requests: int


class ServiceStatusResponse(BaseModel):
    """Response body for PUT /wizard/services/{service_id}/pause and /unpublish."""
    service_id: str
    status: str
    message: str


class AuditLogEntry(BaseModel):
    """A single anonymized audit log entry."""
    timestamp: str
    action_id: str
    outcome: str
    response_code: int | None = None
    latency_ms: int | None = None


class ServiceLogsResponse(BaseModel):
    """Response body for GET /wizard/services/{service_id}/logs."""
    service_id: str
    total_entries: int
    entries: list[AuditLogEntry]
